### ISSUE TITLE
Performance decrease

### ISSUE THREAD

**Issue by dupuisa** [lequal/i-CodeCNES#106] opened 2017-12-08 13:10 UTC
### Expected behavior
At least same performance as V2.0

### Actual behavior
CS company finds out that an analysis launched with eclipse version 3.0.0 takes several minutes while the eclipse version 2.0.0 took several seconds.

### Steps to reproduce behavior
Launch the analyse with eclipse version on a project.

### Detection version
V 3.0.0

**Comment by VincentClaverie** [comment] 2017-12-22 10:56
Eclipse plugin 3.0.0 (on Eclipse Neon) is very (very) slow : more than 30 secondes to analyse 50 lignes.
No problem with IDE release or command line release on the same computer : click and instantaneous result !
Same behaviour on my colleague computer.
And of course it is the eclipse pluging we are interested on !

**Comment by WaldoFR** [comment] 2018-02-09 08:26
Hi @VincentClaverie , 

Could you please show us the JVM args from your `eclipse.ini` file ? If this behaviour only appear when using eclipse's plug-in, it might be due to the -Xms and -Xmx limits set in it.

Regards,
Omar

**Comment by WaldoFR** [comment] 2018-03-19 13:33
Hi,

Performances problems were confirmed during our analysis. Problem was fixed in commit 80a82fd which will be included in the next corrective patch.

Thank you for your report @VincentClaverie & @dupuisa , do not hesitate to add new ones.

Regards,
Omar,

**Closed** 2018-05-24 09:14 UTC
Labels: bug
